---
- name: Parar servicio apache
  service:
      name: apache2
      state: stopped
  tags: config_lb

- name: Balancear
  shell: xr -df --server tcp:0:80 --backend 10.1.3.11:3000 --backend 10.1.3.12:3000 --backend 10.1.3.13:3000 --web-interface 0:8001 & 
  tags: config_lb
