---
- hosts: nas1
  become: yes

  tasks:
      - name: Añadir servidores al grupo de almacenamiento
        shell: "gluster peer probe {{ item }}"
        with_items:
            - 10.1.4.21
            - 10.1.4.22
            - 10.1.4.23

      - name: Verificar el estado del cluster
        command: gluster peer status

      - name: Crear volumen de almacenamiento
        command: gluster volume create nas replica 3 10.1.4.21:/nas/brick 10.1.4.22:/nas/brick 10.1.4.23:/nas/brick force

      - name: Arrancar el cluster
        command: gluster volume start nas

      - name: Comprobar estado del cluster
        command: gluster volume info

      - name: Aumentar valor de timeout
        command: gluster volume set nas network.ping-timeout 5
