---
- hosts: fw
  become: yes

  tasks:
      - name: Transferir archivo
        copy: src=/etc/ansible/roles/fw_conf/files/ dest=/root/ owner=root group=root mode=755 

      - name: Ejecutar archivo
        command: /root/fw.fw


